apiVersion: v1
kind: Secret
metadata:
  name: assisted-installer-rds
  namespace: assisted-installer
  labels:
    app: postgres
type: Opaque
stringData:
  db.host: "postgres"
  db.name: "installer"
  db.password: "admin"
  db.port: "5432"
  db.user: "admin"
