# coding: utf-8

# flake8: noqa
"""
    AssistedInstall

    Assisted installation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from bm_inventory_client.models.block_device import BlockDevice
from bm_inventory_client.models.boot import Boot
from bm_inventory_client.models.cidr import Cidr
from bm_inventory_client.models.cluster import Cluster
from bm_inventory_client.models.cluster_create_params import ClusterCreateParams
from bm_inventory_client.models.cluster_list import ClusterList
from bm_inventory_client.models.cluster_update_params import ClusterUpdateParams
from bm_inventory_client.models.clusterupdateparams_hosts_roles import ClusterupdateparamsHostsRoles
from bm_inventory_client.models.connectivity_check_host import ConnectivityCheckHost
from bm_inventory_client.models.connectivity_check_nic import ConnectivityCheckNic
from bm_inventory_client.models.connectivity_check_params import ConnectivityCheckParams
from bm_inventory_client.models.connectivity_remote_host import ConnectivityRemoteHost
from bm_inventory_client.models.connectivity_report import ConnectivityReport
from bm_inventory_client.models.cpu import Cpu
from bm_inventory_client.models.cpu_details import CpuDetails
from bm_inventory_client.models.credentials import Credentials
from bm_inventory_client.models.debug_step import DebugStep
from bm_inventory_client.models.disk import Disk
from bm_inventory_client.models.error import Error
from bm_inventory_client.models.event import Event
from bm_inventory_client.models.event_list import EventList
from bm_inventory_client.models.free_addresses_request import FreeAddressesRequest
from bm_inventory_client.models.free_network_addresses import FreeNetworkAddresses
from bm_inventory_client.models.free_networks_addresses import FreeNetworksAddresses
from bm_inventory_client.models.host import Host
from bm_inventory_client.models.host_create_params import HostCreateParams
from bm_inventory_client.models.host_install_progress_params import HostInstallProgressParams
from bm_inventory_client.models.host_list import HostList
from bm_inventory_client.models.host_network import HostNetwork
from bm_inventory_client.models.image_create_params import ImageCreateParams
from bm_inventory_client.models.image_info import ImageInfo
from bm_inventory_client.models.ingress_cert_params import IngressCertParams
from bm_inventory_client.models.interface import Interface
from bm_inventory_client.models.introspection import Introspection
from bm_inventory_client.models.inventory import Inventory
from bm_inventory_client.models.l2_connectivity import L2Connectivity
from bm_inventory_client.models.l3_connectivity import L3Connectivity
from bm_inventory_client.models.list_versions import ListVersions
from bm_inventory_client.models.memory import Memory
from bm_inventory_client.models.memory_details import MemoryDetails
from bm_inventory_client.models.nic import Nic
from bm_inventory_client.models.step import Step
from bm_inventory_client.models.step_reply import StepReply
from bm_inventory_client.models.step_type import StepType
from bm_inventory_client.models.steps import Steps
from bm_inventory_client.models.steps_reply import StepsReply
from bm_inventory_client.models.system_vendor import SystemVendor
