# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from bm_inventory_client.models.connectivity_remote_host import ConnectivityRemoteHost  # noqa: F401,E501


class ConnectivityReport(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'remote_hosts': 'list[ConnectivityRemoteHost]'
    }

    attribute_map = {
        'remote_hosts': 'remote_hosts'
    }

    def __init__(self, remote_hosts=None):  # noqa: E501
        """ConnectivityReport - a model defined in Swagger"""  # noqa: E501

        self._remote_hosts = None
        self.discriminator = None

        if remote_hosts is not None:
            self.remote_hosts = remote_hosts

    @property
    def remote_hosts(self):
        """Gets the remote_hosts of this ConnectivityReport.  # noqa: E501


        :return: The remote_hosts of this ConnectivityReport.  # noqa: E501
        :rtype: list[ConnectivityRemoteHost]
        """
        return self._remote_hosts

    @remote_hosts.setter
    def remote_hosts(self, remote_hosts):
        """Sets the remote_hosts of this ConnectivityReport.


        :param remote_hosts: The remote_hosts of this ConnectivityReport.  # noqa: E501
        :type: list[ConnectivityRemoteHost]
        """

        self._remote_hosts = remote_hosts

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConnectivityReport):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
