# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class FreeNetworkAddresses(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'network': 'str',
        'free_addresses': 'list[str]'
    }

    attribute_map = {
        'network': 'network',
        'free_addresses': 'free_addresses'
    }

    def __init__(self, network=None, free_addresses=None):  # noqa: E501
        """FreeNetworkAddresses - a model defined in Swagger"""  # noqa: E501

        self._network = None
        self._free_addresses = None
        self.discriminator = None

        if network is not None:
            self.network = network
        if free_addresses is not None:
            self.free_addresses = free_addresses

    @property
    def network(self):
        """Gets the network of this FreeNetworkAddresses.  # noqa: E501


        :return: The network of this FreeNetworkAddresses.  # noqa: E501
        :rtype: str
        """
        return self._network

    @network.setter
    def network(self, network):
        """Sets the network of this FreeNetworkAddresses.


        :param network: The network of this FreeNetworkAddresses.  # noqa: E501
        :type: str
        """

        self._network = network

    @property
    def free_addresses(self):
        """Gets the free_addresses of this FreeNetworkAddresses.  # noqa: E501


        :return: The free_addresses of this FreeNetworkAddresses.  # noqa: E501
        :rtype: list[str]
        """
        return self._free_addresses

    @free_addresses.setter
    def free_addresses(self, free_addresses):
        """Sets the free_addresses of this FreeNetworkAddresses.


        :param free_addresses: The free_addresses of this FreeNetworkAddresses.  # noqa: E501
        :type: list[str]
        """

        self._free_addresses = free_addresses

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FreeNetworkAddresses):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
