# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class HostCreateParams(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'host_id': 'str',
        'discovery_agent_version': 'str'
    }

    attribute_map = {
        'host_id': 'host_id',
        'discovery_agent_version': 'discovery_agent_version'
    }

    def __init__(self, host_id=None, discovery_agent_version=None):  # noqa: E501
        """HostCreateParams - a model defined in Swagger"""  # noqa: E501

        self._host_id = None
        self._discovery_agent_version = None
        self.discriminator = None

        self.host_id = host_id
        if discovery_agent_version is not None:
            self.discovery_agent_version = discovery_agent_version

    @property
    def host_id(self):
        """Gets the host_id of this HostCreateParams.  # noqa: E501


        :return: The host_id of this HostCreateParams.  # noqa: E501
        :rtype: str
        """
        return self._host_id

    @host_id.setter
    def host_id(self, host_id):
        """Sets the host_id of this HostCreateParams.


        :param host_id: The host_id of this HostCreateParams.  # noqa: E501
        :type: str
        """
        if host_id is None:
            raise ValueError("Invalid value for `host_id`, must not be `None`")  # noqa: E501

        self._host_id = host_id

    @property
    def discovery_agent_version(self):
        """Gets the discovery_agent_version of this HostCreateParams.  # noqa: E501


        :return: The discovery_agent_version of this HostCreateParams.  # noqa: E501
        :rtype: str
        """
        return self._discovery_agent_version

    @discovery_agent_version.setter
    def discovery_agent_version(self, discovery_agent_version):
        """Sets the discovery_agent_version of this HostCreateParams.


        :param discovery_agent_version: The discovery_agent_version of this HostCreateParams.  # noqa: E501
        :type: str
        """

        self._discovery_agent_version = discovery_agent_version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HostCreateParams):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
