# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class HostNetwork(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cidr': 'str',
        'host_ids': 'list[str]'
    }

    attribute_map = {
        'cidr': 'cidr',
        'host_ids': 'host_ids'
    }

    def __init__(self, cidr=None, host_ids=None):  # noqa: E501
        """HostNetwork - a model defined in Swagger"""  # noqa: E501

        self._cidr = None
        self._host_ids = None
        self.discriminator = None

        if cidr is not None:
            self.cidr = cidr
        if host_ids is not None:
            self.host_ids = host_ids

    @property
    def cidr(self):
        """Gets the cidr of this HostNetwork.  # noqa: E501


        :return: The cidr of this HostNetwork.  # noqa: E501
        :rtype: str
        """
        return self._cidr

    @cidr.setter
    def cidr(self, cidr):
        """Sets the cidr of this HostNetwork.


        :param cidr: The cidr of this HostNetwork.  # noqa: E501
        :type: str
        """

        self._cidr = cidr

    @property
    def host_ids(self):
        """Gets the host_ids of this HostNetwork.  # noqa: E501


        :return: The host_ids of this HostNetwork.  # noqa: E501
        :rtype: list[str]
        """
        return self._host_ids

    @host_ids.setter
    def host_ids(self, host_ids):
        """Sets the host_ids of this HostNetwork.


        :param host_ids: The host_ids of this HostNetwork.  # noqa: E501
        :type: list[str]
        """

        self._host_ids = host_ids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HostNetwork):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
