# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ImageCreateParams(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'proxy_url': 'str',
        'ssh_public_key': 'str'
    }

    attribute_map = {
        'proxy_url': 'proxy_url',
        'ssh_public_key': 'ssh_public_key'
    }

    def __init__(self, proxy_url=None, ssh_public_key=None):  # noqa: E501
        """ImageCreateParams - a model defined in Swagger"""  # noqa: E501

        self._proxy_url = None
        self._ssh_public_key = None
        self.discriminator = None

        if proxy_url is not None:
            self.proxy_url = proxy_url
        if ssh_public_key is not None:
            self.ssh_public_key = ssh_public_key

    @property
    def proxy_url(self):
        """Gets the proxy_url of this ImageCreateParams.  # noqa: E501

        The URL of the HTTP/S proxy that agents should use to access the discovery service http://\\<user\\>:\\<password\\>@\\<server\\>:\\<port\\>/   # noqa: E501

        :return: The proxy_url of this ImageCreateParams.  # noqa: E501
        :rtype: str
        """
        return self._proxy_url

    @proxy_url.setter
    def proxy_url(self, proxy_url):
        """Sets the proxy_url of this ImageCreateParams.

        The URL of the HTTP/S proxy that agents should use to access the discovery service http://\\<user\\>:\\<password\\>@\\<server\\>:\\<port\\>/   # noqa: E501

        :param proxy_url: The proxy_url of this ImageCreateParams.  # noqa: E501
        :type: str
        """

        self._proxy_url = proxy_url

    @property
    def ssh_public_key(self):
        """Gets the ssh_public_key of this ImageCreateParams.  # noqa: E501

        SSH public key for debugging the installation.  # noqa: E501

        :return: The ssh_public_key of this ImageCreateParams.  # noqa: E501
        :rtype: str
        """
        return self._ssh_public_key

    @ssh_public_key.setter
    def ssh_public_key(self, ssh_public_key):
        """Sets the ssh_public_key of this ImageCreateParams.

        SSH public key for debugging the installation.  # noqa: E501

        :param ssh_public_key: The ssh_public_key of this ImageCreateParams.  # noqa: E501
        :type: str
        """

        self._ssh_public_key = ssh_public_key

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImageCreateParams):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
