# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from bm_inventory_client.models.cidr import Cidr  # noqa: F401,E501


class Nic(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'state': 'str',
        'mtu': 'int',
        'mac': 'str',
        'cidrs': 'list[Cidr]'
    }

    attribute_map = {
        'name': 'name',
        'state': 'state',
        'mtu': 'mtu',
        'mac': 'mac',
        'cidrs': 'cidrs'
    }

    def __init__(self, name=None, state=None, mtu=None, mac=None, cidrs=None):  # noqa: E501
        """Nic - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._state = None
        self._mtu = None
        self._mac = None
        self._cidrs = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if state is not None:
            self.state = state
        if mtu is not None:
            self.mtu = mtu
        if mac is not None:
            self.mac = mac
        if cidrs is not None:
            self.cidrs = cidrs

    @property
    def name(self):
        """Gets the name of this Nic.  # noqa: E501


        :return: The name of this Nic.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Nic.


        :param name: The name of this Nic.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def state(self):
        """Gets the state of this Nic.  # noqa: E501


        :return: The state of this Nic.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this Nic.


        :param state: The state of this Nic.  # noqa: E501
        :type: str
        """

        self._state = state

    @property
    def mtu(self):
        """Gets the mtu of this Nic.  # noqa: E501


        :return: The mtu of this Nic.  # noqa: E501
        :rtype: int
        """
        return self._mtu

    @mtu.setter
    def mtu(self, mtu):
        """Sets the mtu of this Nic.


        :param mtu: The mtu of this Nic.  # noqa: E501
        :type: int
        """

        self._mtu = mtu

    @property
    def mac(self):
        """Gets the mac of this Nic.  # noqa: E501


        :return: The mac of this Nic.  # noqa: E501
        :rtype: str
        """
        return self._mac

    @mac.setter
    def mac(self, mac):
        """Sets the mac of this Nic.


        :param mac: The mac of this Nic.  # noqa: E501
        :type: str
        """

        self._mac = mac

    @property
    def cidrs(self):
        """Gets the cidrs of this Nic.  # noqa: E501


        :return: The cidrs of this Nic.  # noqa: E501
        :rtype: list[Cidr]
        """
        return self._cidrs

    @cidrs.setter
    def cidrs(self, cidrs):
        """Sets the cidrs of this Nic.


        :param cidrs: The cidrs of this Nic.  # noqa: E501
        :type: list[Cidr]
        """

        self._cidrs = cidrs

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Nic):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
