# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import bm_inventory_client
from bm_inventory_client.api.versions_api import VersionsApi  # noqa: E501
from bm_inventory_client.rest import ApiException


class TestVersionsApi(unittest.TestCase):
    """VersionsApi unit test stubs"""

    def setUp(self):
        self.api = bm_inventory_client.api.versions_api.VersionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_list_component_versions(self):
        """Test case for list_component_versions

        List of componenets versions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
