# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import bm_inventory_client
from bm_inventory_client.api.events_api import EventsApi  # noqa: E501
from bm_inventory_client.rest import ApiException


class TestEventsApi(unittest.TestCase):
    """EventsApi unit test stubs"""

    def setUp(self):
        self.api = bm_inventory_client.api.events_api.EventsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_list_events(self):
        """Test case for list_events

        Lists events for an entity_id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
