# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import bm_inventory_client
from bm_inventory_client.models.steps_reply import StepsReply  # noqa: E501
from bm_inventory_client.rest import ApiException


class TestStepsReply(unittest.TestCase):
    """StepsReply unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStepsReply(self):
        """Test StepsReply"""
        # FIXME: construct object with mandatory attributes with example values
        # model = bm_inventory_client.models.steps_reply.StepsReply()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
