# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import bm_inventory_client
from bm_inventory_client.api.installer_api import InstallerApi  # noqa: E501
from bm_inventory_client.rest import ApiException


class TestInstallerApi(unittest.TestCase):
    """InstallerApi unit test stubs"""

    def setUp(self):
        self.api = bm_inventory_client.api.installer_api.InstallerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_deregister_cluster(self):
        """Test case for deregister_cluster

        Deletes an OpenShift bare metal cluster definition.  # noqa: E501
        """
        pass

    def test_deregister_host(self):
        """Test case for deregister_host

        Deregisters an OpenShift bare metal host.  # noqa: E501
        """
        pass

    def test_disable_host(self):
        """Test case for disable_host

        Disables a host for inclusion in the cluster.  # noqa: E501
        """
        pass

    def test_download_cluster_files(self):
        """Test case for download_cluster_files

        Downloads files relating to the installed/installing cluster.  # noqa: E501
        """
        pass

    def test_download_cluster_iso(self):
        """Test case for download_cluster_iso

        Downloads the OpenShift per-cluster discovery ISO.  # noqa: E501
        """
        pass

    def test_download_cluster_kubeconfig(self):
        """Test case for download_cluster_kubeconfig

        Downloads the kubeconfig file for this cluster.  # noqa: E501
        """
        pass

    def test_enable_host(self):
        """Test case for enable_host

        Enables a host for inclusion in the cluster.  # noqa: E501
        """
        pass

    def test_generate_cluster_iso(self):
        """Test case for generate_cluster_iso

        Creates a new OpenShift per-cluster discovery ISO.  # noqa: E501
        """
        pass

    def test_get_cluster(self):
        """Test case for get_cluster

        Retrieves the details of the OpenShift bare metal cluster.  # noqa: E501
        """
        pass

    def test_get_credentials(self):
        """Test case for get_credentials

        Get the the cluster admin credentials.  # noqa: E501
        """
        pass

    def test_get_host(self):
        """Test case for get_host

        Retrieves the details of the OpenShift bare metal host.  # noqa: E501
        """
        pass

    def test_get_next_steps(self):
        """Test case for get_next_steps

        Retrieves the next operations that the host agent needs to perform.  # noqa: E501
        """
        pass

    def test_install_cluster(self):
        """Test case for install_cluster

        Installs the OpenShift bare metal cluster.  # noqa: E501
        """
        pass

    def test_list_clusters(self):
        """Test case for list_clusters

        Retrieves the list of OpenShift bare metal clusters.  # noqa: E501
        """
        pass

    def test_list_hosts(self):
        """Test case for list_hosts

        Retrieves the list of OpenShift bare metal hosts.  # noqa: E501
        """
        pass

    def test_post_step_reply(self):
        """Test case for post_step_reply

        Posts the result of the operations from the host agent.  # noqa: E501
        """
        pass

    def test_register_cluster(self):
        """Test case for register_cluster

        Creates a new OpenShift bare metal cluster definition.  # noqa: E501
        """
        pass

    def test_register_host(self):
        """Test case for register_host

        Registers a new OpenShift bare metal host.  # noqa: E501
        """
        pass

    def test_set_debug_step(self):
        """Test case for set_debug_step

        Sets a single shot debug step that will be sent next time the host agent will ask for a command.  # noqa: E501
        """
        pass

    def test_update_cluster(self):
        """Test case for update_cluster

        Updates an OpenShift bare metal cluster definition.  # noqa: E501
        """
        pass

    def test_update_host_install_progress(self):
        """Test case for update_host_install_progress

        Update installation progress  # noqa: E501
        """
        pass

    def test_upload_cluster_ingress_cert(self):
        """Test case for upload_cluster_ingress_cert

        Transfer the ingress certificate for the cluster.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
