# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import bm_inventory_client
from bm_inventory_client.models.cluster_create_params import ClusterCreateParams  # noqa: E501
from bm_inventory_client.rest import ApiException


class TestClusterCreateParams(unittest.TestCase):
    """ClusterCreateParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClusterCreateParams(self):
        """Test ClusterCreateParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = bm_inventory_client.models.cluster_create_params.ClusterCreateParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
