kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mariadb-pv-claim
  namespace: assisted-installer
  labels:
    app: mariadb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: REPLACE_STORAGE
