apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: assisted-installer
spec:
  selector:
    matchLabels:
      app: mariadb
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: mariadb-config
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mariadbvol
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 400Mi
      volumes:
        - name: mariadbvol
          persistentVolumeClaim:
            claimName: mariadb-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: assisted-installer
  labels:
    app: mariadb
spec:
  type: LoadBalancer
  ports:
    - port: 3306
  selector:
    app: mariadb
status:
  loadBalancer: {}
