apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: prometheus-k8s-tls
  labels:
    prometheus: assisted-installer-prometheus
  name: prometheus-k8s
  namespace: REPLACE_NAMESPACE
spec:
  ports:
  - name: proxy
    port: 9091
    protocol: TCP
    targetPort: web-proxy
  - name: grafana-access
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    app: prometheus
    prometheus: assisted-installer-prometheus
  type: ClusterIP
