apiVersion: v1
kind: Secret
metadata:
  name: assisted-installer-sso
  namespace: REPLACE_NAMESPACE
  labels:
    app: bm-inventory
type: Opaque
stringData:
  ocm-service.clientId: ""
  ocm-service.clientSecret: ""
