apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: assisted-service
  namespace: REPLACE_NAMESPACE
spec:
  selector:
    matchLabels:
      app: assisted-service
  replicas: 1
  template:
    metadata:
      labels:
        app: assisted-service
    spec:
      containers:
        - name: assisted-service
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 400Mi
          image: REPLACE_IMAGE
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          envFrom:
            - configMapRef:
                name: s3-config
            - configMapRef:
                name: assisted-service-config
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: assisted-installer-rds
                  key: db.host
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: assisted-installer-rds
                  key: db.name
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: assisted-installer-rds
                  key: db.password
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: assisted-installer-rds
                  key: db.port
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: assisted-installer-rds
                  key: db.user
          volumeMounts:
            - name: route53-creds
              mountPath: "/.aws"
              readOnly: true
      volumes:
        - name: route53-creds
          secret:
            secretName: route53-creds
            optional: true
