apiVersion: v1
kind: Service
metadata:
  labels:
    app: bm-inventory
  name: bm-inventory
  namespace: assisted-installer
spec:
  ports:
    - port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    app: bm-inventory
  type: LoadBalancer
status:
  loadBalancer: {}
