apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: s3-object-expirer-cron-job
  namespace: assisted-installer
spec:
  schedule: "@hourly"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: s3-object-expirer-job-pod
            image: REPLACE_IMAGE
            imagePullPolicy: Always
            envFrom:
              - configMapRef:
                  name: s3-config
            args:
            - /bin/bash
            - -c
            -  python ./expirer.py
          restartPolicy: OnFailure
      backoffLimit: 3
