apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scality
  name: scality
  namespace: assisted-installer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scality
  template:
    metadata:
      labels:
        app: scality
    spec:
      containers:
        - image: scality/s3server
          imagePullPolicy: Always
          name: s3server
          envFrom:
            - configMapRef:
                name: s3-config
          volumeMounts:
            - mountPath: /mnt/data
              name: scalityvol
      volumes:
        - name: scalityvol
          persistentVolumeClaim:
            claimName: scality-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: scality
  name: scality
  namespace: assisted-installer
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: scality
  type: LoadBalancer
status:
  loadBalancer: {}
