kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: scality-pv-claim
  namespace: REPLACE_NAMESPACE
  labels:
    app: scality
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
