apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scality
  name: scality
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scality
  template:
    metadata:
      labels:
        app: scality
    spec:
      containers:
        - image: scality/s3server
          imagePullPolicy: Always
          name: s3server
          envFrom:
            - configMapRef:
                name: s3-config
          volumeMounts:
            - mountPath: /mnt/data
              name: scalityvol
          resources:
            limits:
              cpu: 500m
              memory: 2000Mi
            requests:
              cpu: 300m
              memory: 2000Mi
      volumes:
        - name: scalityvol
          persistentVolumeClaim:
            claimName: scality-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: scality
  # cloudserver-front supported as one of the default hostnames that can receive messages
  # to support other hostnamnes they need to be defined with HOST_NAME environment variable.
  name: cloudserver-front
  namespace: REPLACE_NAMESPACE
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: scality
  clusterIP: None
status:
  loadBalancer: {}
