// Code generated by go-swagger; DO NOT EDIT.

package inventory

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostStepReplyCreatedCode is the HTTP code returned for type PostStepReplyCreated
const PostStepReplyCreatedCode int = 201

/*PostStepReplyCreated Reply accepted

swagger:response postStepReplyCreated
*/
type PostStepReplyCreated struct {
}

// NewPostStepReplyCreated creates PostStepReplyCreated with default headers values
func NewPostStepReplyCreated() *PostStepReplyCreated {

	return &PostStepReplyCreated{}
}

// WriteResponse to the client
func (o *PostStepReplyCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// PostStepReplyNotFoundCode is the HTTP code returned for type PostStepReplyNotFound
const PostStepReplyNotFoundCode int = 404

/*PostStepReplyNotFound Node not found

swagger:response postStepReplyNotFound
*/
type PostStepReplyNotFound struct {
}

// NewPostStepReplyNotFound creates PostStepReplyNotFound with default headers values
func NewPostStepReplyNotFound() *PostStepReplyNotFound {

	return &PostStepReplyNotFound{}
}

// WriteResponse to the client
func (o *PostStepReplyNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
