// Code generated by go-swagger; DO NOT EDIT.

package installer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/filanov/bm-inventory/models"
)

// UpdateHostClusterOKCode is the HTTP code returned for type UpdateHostClusterOK
const UpdateHostClusterOKCode int = 200

/*UpdateHostClusterOK Success.

swagger:response updateHostClusterOK
*/
type UpdateHostClusterOK struct {
}

// NewUpdateHostClusterOK creates UpdateHostClusterOK with default headers values
func NewUpdateHostClusterOK() *UpdateHostClusterOK {

	return &UpdateHostClusterOK{}
}

// WriteResponse to the client
func (o *UpdateHostClusterOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// UpdateHostClusterNotFoundCode is the HTTP code returned for type UpdateHostClusterNotFound
const UpdateHostClusterNotFoundCode int = 404

/*UpdateHostClusterNotFound Error.

swagger:response updateHostClusterNotFound
*/
type UpdateHostClusterNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateHostClusterNotFound creates UpdateHostClusterNotFound with default headers values
func NewUpdateHostClusterNotFound() *UpdateHostClusterNotFound {

	return &UpdateHostClusterNotFound{}
}

// WithPayload adds the payload to the update host cluster not found response
func (o *UpdateHostClusterNotFound) WithPayload(payload *models.Error) *UpdateHostClusterNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update host cluster not found response
func (o *UpdateHostClusterNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateHostClusterNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateHostClusterInternalServerErrorCode is the HTTP code returned for type UpdateHostClusterInternalServerError
const UpdateHostClusterInternalServerErrorCode int = 500

/*UpdateHostClusterInternalServerError Error.

swagger:response updateHostClusterInternalServerError
*/
type UpdateHostClusterInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateHostClusterInternalServerError creates UpdateHostClusterInternalServerError with default headers values
func NewUpdateHostClusterInternalServerError() *UpdateHostClusterInternalServerError {

	return &UpdateHostClusterInternalServerError{}
}

// WithPayload adds the payload to the update host cluster internal server error response
func (o *UpdateHostClusterInternalServerError) WithPayload(payload *models.Error) *UpdateHostClusterInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update host cluster internal server error response
func (o *UpdateHostClusterInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateHostClusterInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
