// Code generated by go-swagger; DO NOT EDIT.

package installer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUpdateHostClusterParams creates a new UpdateHostClusterParams object
// with the default values initialized.
func NewUpdateHostClusterParams() *UpdateHostClusterParams {
	var ()
	return &UpdateHostClusterParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateHostClusterParamsWithTimeout creates a new UpdateHostClusterParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateHostClusterParamsWithTimeout(timeout time.Duration) *UpdateHostClusterParams {
	var ()
	return &UpdateHostClusterParams{

		timeout: timeout,
	}
}

// NewUpdateHostClusterParamsWithContext creates a new UpdateHostClusterParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateHostClusterParamsWithContext(ctx context.Context) *UpdateHostClusterParams {
	var ()
	return &UpdateHostClusterParams{

		Context: ctx,
	}
}

// NewUpdateHostClusterParamsWithHTTPClient creates a new UpdateHostClusterParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateHostClusterParamsWithHTTPClient(client *http.Client) *UpdateHostClusterParams {
	var ()
	return &UpdateHostClusterParams{
		HTTPClient: client,
	}
}

/*UpdateHostClusterParams contains all the parameters to send to the API endpoint
for the update host cluster operation typically these are written to a http.Request
*/
type UpdateHostClusterParams struct {

	/*ClusterID*/
	ClusterID strfmt.UUID
	/*DestClusterID*/
	DestClusterID strfmt.UUID
	/*HostID*/
	HostID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update host cluster params
func (o *UpdateHostClusterParams) WithTimeout(timeout time.Duration) *UpdateHostClusterParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update host cluster params
func (o *UpdateHostClusterParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update host cluster params
func (o *UpdateHostClusterParams) WithContext(ctx context.Context) *UpdateHostClusterParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update host cluster params
func (o *UpdateHostClusterParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update host cluster params
func (o *UpdateHostClusterParams) WithHTTPClient(client *http.Client) *UpdateHostClusterParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update host cluster params
func (o *UpdateHostClusterParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClusterID adds the clusterID to the update host cluster params
func (o *UpdateHostClusterParams) WithClusterID(clusterID strfmt.UUID) *UpdateHostClusterParams {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the update host cluster params
func (o *UpdateHostClusterParams) SetClusterID(clusterID strfmt.UUID) {
	o.ClusterID = clusterID
}

// WithDestClusterID adds the destClusterID to the update host cluster params
func (o *UpdateHostClusterParams) WithDestClusterID(destClusterID strfmt.UUID) *UpdateHostClusterParams {
	o.SetDestClusterID(destClusterID)
	return o
}

// SetDestClusterID adds the destClusterId to the update host cluster params
func (o *UpdateHostClusterParams) SetDestClusterID(destClusterID strfmt.UUID) {
	o.DestClusterID = destClusterID
}

// WithHostID adds the hostID to the update host cluster params
func (o *UpdateHostClusterParams) WithHostID(hostID strfmt.UUID) *UpdateHostClusterParams {
	o.SetHostID(hostID)
	return o
}

// SetHostID adds the hostId to the update host cluster params
func (o *UpdateHostClusterParams) SetHostID(hostID strfmt.UUID) {
	o.HostID = hostID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateHostClusterParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cluster_id
	if err := r.SetPathParam("cluster_id", o.ClusterID.String()); err != nil {
		return err
	}

	// query param dest_cluster_id
	qrDestClusterID := o.DestClusterID
	qDestClusterID := qrDestClusterID.String()
	if qDestClusterID != "" {
		if err := r.SetQueryParam("dest_cluster_id", qDestClusterID); err != nil {
			return err
		}
	}

	// path param host_id
	if err := r.SetPathParam("host_id", o.HostID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
