name: image-push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        sudo pip install strato-skipper
        mkdir -p ~/.docker
        echo "{}" > ~/.docker/config.json
        touch ${HOME}/.gitconfig
        ln -s Dockerfile.bm-inventory Dockerfile
    - name: build
      run: |
        skipper make build
        skipper make update_revision_file
    - name: Get release version
      id: get_version
      run: echo ::set-env name=GIT_REVISION::$(echo ${GITHUB_SHA})
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@2.15
      with:
        name: bm-inventory
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        REGISTRY: 'quay.io/ocpmetal'
        dockerfile: "Dockerfile.bm-inventory"
        buildargs: GIT_REVISION
        tags: "stable,${{ env.GIT_REVISION }}"
