// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// MoveParams move params
//
// swagger:model move_params
type MoveParams struct {

	// dest cluster id
	// Required: true
	// Format: uuid
	DestClusterID *strfmt.UUID `json:"dest_cluster_id"`
}

// Validate validates this move params
func (m *MoveParams) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDestClusterID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MoveParams) validateDestClusterID(formats strfmt.Registry) error {

	if err := validate.Required("dest_cluster_id", "body", m.DestClusterID); err != nil {
		return err
	}

	if err := validate.FormatOf("dest_cluster_id", "body", "uuid", m.DestClusterID.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *MoveParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MoveParams) UnmarshalBinary(b []byte) error {
	var res MoveParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
